/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      "mobile": "480px",
      "tablet": "768px",
      "laptop": "1024px",
      "desktop": "1440px",
    },
    extend: {
      colors: {
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        elevated: "var(--color-elevated)",
        border: "var(--color-border)",
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          disabled: "var(--color-text-disabled)",
        },
        accent: {
          primary: "var(--color-accent-primary)",
          secondary: "var(--color-accent-secondary)",
        },
        status: {
          success: "var(--color-status-success)",
          warning: "var(--color-status-warning)",
          error: "var(--color-status-error)",
          info: "var(--color-status-info)",
        },
        state: {
          hover: "var(--color-state-hover)",
          focus: "var(--color-state-focus)",
          selection: "var(--color-state-selection)",
          disabledBg: "var(--color-state-disabled-bg)",
        },
        agent: {
          idle: "var(--color-agent-idle)",
          negotiating: "var(--color-agent-negotiating)",
          executing: "var(--color-agent-executing)",
          success: "var(--color-agent-success)",
          blocked: "var(--color-agent-blocked)",
        },
        grid: {
          busbar: "var(--color-grid-busbar)",
          transformer: "var(--color-grid-transformer)",
          generator: "var(--color-grid-generator)",
          load: "var(--color-grid-load)",
          lineActive: "var(--color-grid-line-active)",
          lineTripped: "var(--color-grid-line-tripped)",
        },
      },
      fontFamily: {
        heading: ["var(--font-heading)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        display: ["3.0rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        h1: ["2.25rem", { lineHeight: "1.3", letterSpacing: "-0.02em" }],
        h2: ["1.5rem", { lineHeight: "1.4", letterSpacing: "-0.02em" }],
        h3: ["1.125rem", { lineHeight: "1.5", letterSpacing: "-0.02em" }],
        h4: ["0.95rem", { lineHeight: "1.45", letterSpacing: "-0.02em" }],
        h5: ["0.85rem", { lineHeight: "1.4", letterSpacing: "-0.02em" }],
        h6: ["0.75rem", { lineHeight: "1.35", letterSpacing: "-0.02em" }],
        subtitle: ["1.05rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
        "body-large": ["1.125rem", { lineHeight: "1.55", letterSpacing: "-0.01em" }],
        body: ["0.95rem", { lineHeight: "1.6", letterSpacing: "-0.01em" }],
        "body-small": ["0.85rem", { lineHeight: "1.55", letterSpacing: "-0.01em" }],
        caption: ["0.75rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
        label: ["0.75rem", { lineHeight: "1.35", letterSpacing: "0.05em" }],
        button: ["0.85rem", { lineHeight: "1.4", letterSpacing: "0.05em" }],
        code: ["0.75rem", { lineHeight: "1.35", letterSpacing: "0.02em" }],
      },
      spacing: {
        "sp-1": "var(--sp-1)",
        "sp-2": "var(--sp-2)",
        "sp-3": "var(--sp-3)",
        "sp-4": "var(--sp-4)",
        "sp-5": "var(--sp-5)",
        "sp-6": "var(--sp-6)",
        "sp-7": "var(--sp-7)",
        "sp-8": "var(--sp-8)",
        "sp-9": "var(--sp-9)",
        "sp-10": "var(--sp-10)",
        "sp-11": "var(--sp-11)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sharp: "var(--radius-sharp)",
        card: "var(--radius-card)",
        badge: "var(--radius-badge)",
      },
      boxShadow: {
        none: "var(--shadow-none)",
        card: "var(--shadow-card)",
        dropdown: "var(--shadow-dropdown)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        fixed: "var(--z-fixed)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
      },
      transitionDuration: {
        fast: "var(--motion-duration-fast)",
        standard: "var(--motion-duration-standard)",
        immediate: "var(--motion-duration-immediate)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
        linear: "var(--motion-easing-linear)",
      },
    },
  },
  plugins: [],
};
